### ISSUE TITLE
CSS Inheritence

### ISSUE THREAD

**Issue by cyouh95** [malateec/prj-rev-bwfs-dasmoto#2]
Instead of specifying `font-family: Helvetica;` for each individual elements, you could specify it just once for the entire `body` element and all its children elements would inherit this property.

```css
body {
  font-family: Helvetica;
}
```

https://github.com/malateec/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/style.css
